// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// import 'firebase_options.dart';

// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA0b5mrqmgpMnW8Z1-hpcFVJbGHl8SjusY',
//     appId: '1:783896184316:web:a2f503ce13534ac626de79',
//     messagingSenderId: '783896184316',
//     projectId: 'captain-8156d',
//     authDomain: 'captain-8156d.firebaseapp.com',
//     storageBucket: 'captain-8156d.appspot.com',
//     measurementId: 'G-3N85WMJC74',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDCf9l_KxouUlgmmskzLxe8EpUr5dzZ0KE',
//     appId: '1:783896184316:android:a4da606eda0ed00526de79',
//     messagingSenderId: '783896184316',
//     projectId: 'captain-8156d',
//     storageBucket: 'captain-8156d.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCZDynXRLEb2KSx6Dh3KpbL97vdyHJK4DM',
//     appId: '1:783896184316:ios:9521f387730dbe8626de79',
//     messagingSenderId: '783896184316',
//     projectId: 'captain-8156d',
//     storageBucket: 'captain-8156d.appspot.com',
//     iosBundleId: 'com.example.captain',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCZDynXRLEb2KSx6Dh3KpbL97vdyHJK4DM',
//     appId: '1:783896184316:ios:fdd0646f81158ff026de79',
//     messagingSenderId: '783896184316',
//     projectId: 'captain-8156d',
//     storageBucket: 'captain-8156d.appspot.com',
//     iosBundleId: 'com.example.captain.RunnerTests',
//   );
// }
