// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pMCqm--4RYbQI89sJON7aNTKD_pu9LI',
    appId: '1:720970031224:web:7197afdfeb317358d58d8d',
    messagingSenderId: '720970031224',
    projectId: 'the-wall-e0bf3',
    authDomain: 'the-wall-e0bf3.firebaseapp.com',
    storageBucket: 'the-wall-e0bf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ46NPNsyB-uTJHz89uyjL2aJ9mTuXSjA',
    appId: '1:720970031224:android:7b08acd8826ca0cdd58d8d',
    messagingSenderId: '720970031224',
    projectId: 'the-wall-e0bf3',
    storageBucket: 'the-wall-e0bf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4q-DfpMv24ChaFK0E65taf6ppsUa73g',
    appId: '1:720970031224:ios:9e94de0b16431843d58d8d',
    messagingSenderId: '720970031224',
    projectId: 'the-wall-e0bf3',
    storageBucket: 'the-wall-e0bf3.appspot.com',
    iosBundleId: 'com.example.quizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW4q-DfpMv24ChaFK0E65taf6ppsUa73g',
    appId: '1:720970031224:ios:9e94de0b16431843d58d8d',
    messagingSenderId: '720970031224',
    projectId: 'the-wall-e0bf3',
    storageBucket: 'the-wall-e0bf3.appspot.com',
    iosBundleId: 'com.example.quizz',
  );
}
