// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVysahqKapf6FIWMp622mSvj9L7LUKupw',
    appId: '1:201790637251:web:4a75e0f2359caf6c5f4e76',
    messagingSenderId: '201790637251',
    projectId: 'rooms-3ddf2',
    authDomain: 'rooms-3ddf2.firebaseapp.com',
    storageBucket: 'rooms-3ddf2.appspot.com',
    measurementId: 'G-56QN2S6XE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFcnpEbiRDgRI_sM3lZw67qvVUjHFD0tQ',
    appId: '1:201790637251:android:d5365200cd386ed25f4e76',
    messagingSenderId: '201790637251',
    projectId: 'rooms-3ddf2',
    storageBucket: 'rooms-3ddf2.appspot.com',
  );
}
